# Support Vector Machine (SVM)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
!git clone https://github.com/AdSh0102/CogoportPythonTitanic.git

Cloning into 'CogoportPythonTitanic'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (5/5), 33.75 KiB | 280.00 KiB/s, done.

In [3]:
dataset = pd.read_csv('/content/CogoportPythonTitanic/train.csv')
X = dataset.drop(columns=['Survived'])
y = dataset[['Survived']]

## Data Preprocessing (removing columns that might not be useful)

In [4]:
X.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# Calculate the total number of rows in the DataFrame
total_rows = len(X)

# Calculate the number of null values in each column
null_counts = X.isnull().sum()

# Calculate the percentage of null values in each column
null_percentages = (null_counts / total_rows) * 100

# Display the percentage of null values in each column
print(null_percentages)

PassengerId     0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [6]:
X = X.drop('Cabin', axis=1)
X = X.drop('Name', axis=1)
# drop as high %age of missing values

In [7]:
X.columns

Index(['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Embarked'],
      dtype='object')

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## More data preprocessing (handling the remaining null values)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

columns_to_impute = ['Age']
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_test[columns_to_impute])

X_test[columns_to_impute] = imputer.transform(X_test[columns_to_impute])

In [ ]:
# Step 1: Find the mode of the column
mode_value = X_test['Embarked'].mode()[0]

# Step 2: Replace the null values with the mode
X_test['Embarked'].fillna(mode_value, inplace=True)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

columns_to_impute = ['Age']
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_train[columns_to_impute])

X_train[columns_to_impute] = imputer.transform(X_train[columns_to_impute])

In [ ]:
# Step 1: Find the mode of the column
mode_value = X_train['Embarked'].mode()[0]

# Step 2: Replace the null values with the mode
X_train['Embarked'].fillna(mode_value, inplace=True)

In [ ]:
# Calculate the total number of rows in the DataFrame
total_rows = len(X_train)

# Calculate the number of null values in each column
null_counts = X_train.isnull().sum()

# Calculate the percentage of null values in each column
null_percentages = (null_counts / total_rows) * 100

# Display the percentage of null values in each column
print(null_percentages)

In [ ]:
# Calculate the total number of rows in the DataFrame
total_rows = len(X_test)

# Calculate the number of null values in each column
null_counts = X_test.isnull().sum()

# Calculate the percentage of null values in each column
null_percentages = (null_counts / total_rows) * 100

# Display the percentage of null values in each column
print(null_percentages)

## Encoding the variables with categorical data

In [ ]:
X_train.dtypes

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train['Sex'] = le.fit_transform(X_train['Sex'])
X_train['Embarked'] = le.fit_transform(X_train['Embarked'])
X_train['Ticket'] = le.fit_transform(X_train['Ticket'])
X_test['Sex'] = le.fit_transform(X_test['Sex'])
X_test['Embarked'] = le.fit_transform(X_test['Embarked'])
X_test['Ticket'] = le.fit_transform(X_test['Ticket'])

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)